"""Turn notebook cells into a declaration module: the engine behind `%%lc_tool` and `labconstrictor-tools export-notebook`.

An author writes a normal function in a cell. This module
  1. adds the @tool decorator (if missing) and keeps only what belongs in a module (imports, definitions, constants),
  2. checks the result in isolation: names that only exist elsewhere in the notebook are reported, so the exported
     module does not break later in a worker process, and the declaration is validated like `check` does,
  3. writes the cell into a generated module as a managed block, replaced in place on every re-export.
"""

import ast
import builtins
import dis
import json
import os
import re
import logging
import tempfile
from pathlib import Path

PRELUDE = """\
from pathlib import Path
from typing import Annotated, Literal, Optional

from labconstrictor_tools import (
    Affine, ApplyTo, Axes, Description, File, FileOut, Image, ImageOut, Label, Labels, LabelsOut, Max, Min,
    Name, PixelSizeOf, Scalars, Table, TableOut, ToolError, Unit, check_cancel, progress, tool,
)
"""

HEADER = '''"""Tool declarations GENERATED by labconstrictor-tools from a notebook. Edit the notebook, not this file:
re-exporting replaces the blocks between the `# >>> lc-tool` and `# <<< lc-tool` markers."""

'''

_BLOCK = "# >>> lc-tool: %s\n%s# <<< lc-tool: %s\n"
_BLOCK_RE = r"# >>> lc-tool: %s\n.*?# <<< lc-tool: %s\n"


class CellError(Exception):
    """The cell cannot become a tool; the message tells the author what to change."""


class Prepared:
    def __init__(self, name, code, dropped):
        self.name, self.code, self.dropped = name, code, dropped
        self.problems, self.warnings = [], []


# ------------------------------------------------------------------ cell -> module text
def prepare(source, label=None, function=None):
    try:
        tree = ast.parse(source)
    except SyntaxError as error:
        raise CellError(
            "the cell is not plain Python (line %s: %s) - remove %% / ! commands" % (error.lineno, error.msg)
        ) from error
    functions = [n for n in tree.body if isinstance(n, ast.FunctionDef)]
    decorated = [n for n in functions if any(_is_tool_decorator(d) for d in n.decorator_list)]
    if function:
        targets = [n for n in functions if n.name == function]
        if not targets:
            raise CellError("no function named %r in the cell" % function)
    elif len(decorated) == 1:
        targets = decorated
    elif len(functions) == 1:
        targets = functions
    elif not functions:
        raise CellError("the cell defines no function; a tool is a function with typed parameters")
    else:
        raise CellError(
            "the cell defines %d functions (%s); say which is the tool with --function NAME"
            % (len(functions), ", ".join(f.name for f in functions))
        )
    target = targets[0]
    lines = source.splitlines()
    kept, dropped = [], []
    for node in tree.body:
        first = min([node.lineno] + [d.lineno for d in getattr(node, "decorator_list", [])])
        text = lines[first - 1 : node.end_lineno]
        if node is target and not any(_is_tool_decorator(d) for d in node.decorator_list):
            text = ["@tool(%s)" % json.dumps(label) if label else "@tool()"] + text
        if _belongs_in_module(node):
            kept.append("\n".join(text))
        else:
            dropped.append(lines[node.lineno - 1].strip()[:60])
    return Prepared(target.name, "\n\n\n".join(kept) + "\n", dropped)


def _is_tool_decorator(node):
    node = node.func if isinstance(node, ast.Call) else node
    return (isinstance(node, ast.Name) and node.id == "tool") or (
        isinstance(node, ast.Attribute) and node.attr == "tool"
    )


def _belongs_in_module(node):
    if isinstance(node, (ast.Import, ast.ImportFrom, ast.FunctionDef, ast.ClassDef)):
        return True
    if isinstance(node, (ast.Assign, ast.AnnAssign)) and node.value is not None:
        try:
            ast.literal_eval(node.value)
            return True
        except ValueError:
            return False
    return False


# ------------------------------------------------------------------ isolated check
def check(prepared):
    """Fills prepared.problems / prepared.warnings."""
    from .decorators import forget_module
    from .introspection import DeclarationError, describe_tool

    modname = "_lc_cell_check_%s" % prepared.name
    namespace = {"__name__": modname}
    try:
        exec(PRELUDE, namespace)  # noqa: S102 - the author's own code, run in the author's own kernel
        exec(compile(prepared.code, "<cell %s>" % prepared.name, "exec"), namespace)  # noqa: S102
        function = namespace[prepared.name]
        missing = sorted(_free_names(compile(prepared.code, "<cell>", "exec"), namespace))
        if missing:
            prepared.problems.append(
                "uses %s, defined elsewhere in the notebook - import it or define it inside the cell"
                % ", ".join(repr(m) for m in missing)
            )
        describe_tool(function.__lc_tool__)
    except NameError as error:
        prepared.problems.append(
            "uses %r, defined elsewhere in the notebook - import it or define it inside the cell"
            % (getattr(error, "name", None) or str(error))
        )
    except DeclarationError as error:
        prepared.problems.append("invalid declaration: %s" % error)
    except Exception as error:  # noqa: BLE001 - whatever the cell raises is the finding (reported as a problem, and logged with its traceback)
        logging.getLogger("labconstrictor.exporter").error("tool cell %r fails on its own", prepared.name, exc_info=True)
        prepared.problems.append("the cell fails on its own: %s: %s" % (type(error).__name__, error))
    finally:
        forget_module(modname)
    from .cli import HEAVY_MODULES

    for node in ast.parse(prepared.code).body:
        names = (
            [a.name for a in node.names]
            if isinstance(node, ast.Import)
            else [node.module or ""] if isinstance(node, ast.ImportFrom) else []
        )
        heavy = sorted({n.split(".")[0] for n in names} & set(HEAVY_MODULES))
        if heavy:
            prepared.warnings.append(
                "imports %s at module level - move it inside the function so that browsing tools stays instant"
                % ", ".join(heavy)
            )
    if prepared.dropped:
        prepared.warnings.append(
            "not exported (only imports, definitions and constants are): %s" % "; ".join(prepared.dropped)
        )
    return prepared


def _free_names(module_code, namespace):
    """Global names used inside functions that neither the module nor the builtins define."""
    found = set()

    def walk(code):
        for inst in dis.get_instructions(code):
            if inst.opname == "LOAD_GLOBAL":
                found.add(inst.argval)
        for const in code.co_consts:
            if hasattr(const, "co_code"):
                walk(const)

    walk(module_code)
    return {n for n in found if n not in namespace and not hasattr(builtins, n)}


# ------------------------------------------------------------------ writing the module
def export(path, prepared_cells):
    """Replace (or append) one managed block per cell in `path`; everything else in the file is kept."""
    path = Path(path)
    text = path.read_text(encoding="utf-8") if path.exists() else HEADER + PRELUDE + "\n\n"
    for cell in prepared_cells:
        block = _BLOCK % (cell.name, cell.code, cell.name)
        pattern = re.compile(_BLOCK_RE % (re.escape(cell.name), re.escape(cell.name)), re.S)
        text = (
            pattern.sub(lambda _m, b=block: b, text)
            if pattern.search(text)
            else text.rstrip("\n") + "\n\n\n" + block
        )
    handle, temporary = tempfile.mkstemp(dir=str(path.resolve().parent), suffix=".tmp")
    with os.fdopen(handle, "w", encoding="utf-8") as stream:
        stream.write(text)
    os.replace(temporary, path)
    return path


# ------------------------------------------------------------------ notebook files
MAGIC = "%%lc_tool"


def parse_magic_line(line):
    """'%%lc_tool "Label" --export lc_tools.py --function f --no-form' -> argparse namespace."""
    import argparse
    import shlex

    parser = argparse.ArgumentParser(prog=MAGIC, add_help=False)
    parser.add_argument("label", nargs="?")
    parser.add_argument("--export", nargs="?", const="lc_tools.py")
    parser.add_argument("--function")
    parser.add_argument("--no-form", action="store_true")
    return parser.parse_args(shlex.split(line))


def cells_of(notebook_path):
    """(magic_line_arguments, source) for every %%lc_tool cell of an .ipynb file (plain JSON, no nbformat)."""
    notebook = json.loads(Path(notebook_path).read_text(encoding="utf-8"))
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        source = cell["source"] if isinstance(cell["source"], str) else "".join(cell["source"])
        first, _, rest = source.partition("\n")
        if first.strip().startswith(MAGIC):
            yield parse_magic_line(first.strip()[len(MAGIC) :]), rest


def export_notebook(notebook_path, out_path):
    """Returns (prepared_cells, errors). Nothing is written when any cell has problems."""
    prepared, errors = [], []
    for number, (arguments, source) in enumerate(cells_of(notebook_path), 1):
        try:
            cell = check(prepare(source, arguments.label, arguments.function))
        except CellError as error:
            errors.append("tool cell %d: %s" % (number, error))
            continue
        errors += ["%s: %s" % (cell.name, p) for p in cell.problems]
        prepared.append(cell)
    if not prepared and not errors:
        errors.append("no %%lc_tool cells in %s" % notebook_path)
    if not errors:
        export(out_path, prepared)
    return prepared, errors


__all__ = ["prepare", "check", "export", "export_notebook", "CellError", "PRELUDE"]
